[package]
name = "ego-tree"
edition = "2024"
version = "0.11.0"
description = "Vec-backed ID-tree"
categories = ["data-structures", "no-std"]
keywords = ["tree", "vec", "id", "index"]
authors = [
    "June McEnroe <june@causal.agency>",
    "Carlo Federico Vescovo <vescovocarlofederico@gmail.com>",
]
license = "ISC"
repository = "https://github.com/rust-scraper/ego-tree"
readme = "README.md"

[features]
serde = ["dep:serde_core"]

[dependencies]
serde_core = { version = "1.0.209", default-features = false, features = ["alloc"], optional = true }

[dev-dependencies]
serde_core = "1.0.209"
serde_test = "1.0.177"
